### PR TITLE
meta-qt6: upgrade to latest 6.6.2

### PR DESCRIPTION
**Pull request by shr-project**

### CODE REVIEW

**Comment by Tofee** [comment]
Why not take the last commit in 6.6.2 branch ? It looks like you're missing one last commit that updates quite some recipes' SRCREV

**Comment by shr-project** [comment]
> Why not take the last commit in 6.6.2 branch ? It looks like you're missing one last commit that updates quite some recipes' SRCREV

because code.qt.io is down this weekend, fixed now

**Review by Tofee — APPROVED** [review]
All good, at least on pinephone target

**Comment by Herrie82** [comment]
Let's merge it and take it from there and fix issues when they appear

**Review by Herrie82 — COMMENTED** [review]
LGTM

**Pull request merged**
